version: "3.3"
services:
  ssh-client:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: ssh-client
    volumes:
      - ./init-config:/config/custom-cont-init.d
  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: ssh-server
    volumes:
      - ./init-config:/config/custom-cont-init.d
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_NAME=myuser
      - USER_PASSWORD=password
  some-server:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: some-server
    volumes:
      - ./init-config:/config/custom-cont-init.d
  ssh-jumphost:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: ssh-jumphost
    volumes:
      - ./init-config:/config/custom-cont-init.d
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_NAME=myuser
      - USER_PASSWORD=password
  test-client:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: test-client
    volumes:
      - ./init-config:/config/custom-cont-init.d
